### ISSUE TITLE
Hope to add a variant that can display description

### ISSUE THREAD

**Issue by HunterPR0** [RobZombie9043/horizon-es-de#1]
This theme is awesome, I love it.

This is not an issue, this is a suggestion and request.

I hope you can add a variant that can show descriptions, like the Epic Noir (Revisited) theme, which only shows the text list, cover image with video, description.

![epic-noir-revisited-es-de_02](https://github.com/user-attachments/assets/83674ce8-8a52-4875-bca9-ca3ff9d3e8c4)

Thank you very much for your great work

**Comment by RobZombie9043** [comment]
I was intentionally trying to keep this theme relatively clean and simple but I can have a look what it looks like with the description added in when I get a chance

**Comment by RobZombie9043** [comment]
I think this works ok, I'll look to add it as a variant.

![Horizon with metadata](https://github.com/user-attachments/assets/d6b4cfd9-55f0-436a-b223-4f3ca402566d)

**Comment by RobZombie9043** [comment]
Update is live now on theme downloader.

**Comment by HunterPR0** [comment]
> 我认为这可行，我会考虑将其添加为变体。
> 
> ![带有元数据的 Horizo​​n](https://private-user-images.githubusercontent.com/77545967/359327147-d6b4cfd9-55f0-436a-b223-4f3ca402566d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTI1ODEsIm5iZiI6MTcyNTI1MjI4MSwicGF0aCI6Ii83NzU0NTk2Ny8zNTkzMjcxNDctZDZiNGNmZDktNTVmMC00MzZhLWIyMjMtNGYzY2E0MDI1NjZkLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA0NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDIxNTY0NjM0NTQyZTE2ODQ2Nzk2NTE2OWM2ZGExNTU2YzFkNjVhYTI5Yjg5NjkzNTM3YTZjZWIxNWI5ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l_kFX5iEDwdgJZDAUSRjnKxyIt4treWI0vDsjm_Hsx8)

This is so cool, I really like it, including the other variants you updated, they are all great! Thank you.
